config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'orders/show'
  end
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  
  scope module: :public do
    resources :items
    resources :cart_items
    resources :address
    get 'orders/done', to: 'orders#done', as: 'orders_done'
    post "orders/confirm" => "orders#show"
    resources :orders
    root to: 'homes#top'
    get "items" => "items#index"
    get "items/:id" => "items#show"
    get "customers/mypage" => "customers#show"
    get "customers/information/edit" => "customers#edit"
    patch "customers/information" => "customers#update"
    get "customers/check" => "customers#check"
    patch "customers/leave" => "customers#leave"
    get "cart_items" => "cart_items#index"
    post "cart_items" => "cart_items#create"
    delete "cart_items" => "cart_items#destroy_all", as: "destroy_all"
    # get "address" => "address#index"
    # post "address" => "address#create"
    # get "address/:id/edit" => "address#edit"
    # patch "address/:id" => "address#update"
    # delete "address/:id" => "address#destroy"
    
  end


  namespace :admin do
    root to: 'homes#top'
    resources :customers
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items
    resources :orders
    resources :order_details
    get "genres" => "genres#index"
    post "genres" => "genres#create"
    get "genres/:id/edit" => "genres#edit"
    patch "genres/:id" => "genres#update"
    get "admin/items" => "items#index"
    get "admin/items/new" => "items#new"
    post "admin/items" => "items#create"
    # get "admin/items/:id" => "items#show"
    # get "admin/items/:id/edit" => "items/edit"
    # patch "admin/items/:id" => "items/update"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items
  #has_many :order_details
  enum is_sale: {"販売中":true, "販売停止中":false}
  #with_options presence: true do
   #validates :name, presence: true
   #validates :explanation, presence: true
   #validates :tax_excluded_price, presence: true
   
  #end
  has_one_attached :image
  
  def tax_included_price
    (self.tax_excluded_price * 1.1).floor
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def index
    @items = Item.all
    @item = Item.new
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params) #データを新規登録するためのインスタンス生成
      if @item.save
      redirect_to admin_item_path(@item)
      else
      render "show"
      end
  end

  def show
    @item = Item.find(params[:id])
    @items = Item.all
  end

  def edit
  end

  def update
  end

  private

  def item_params
    params.require(:item).permit(:genre_id, :name, :explanation, :tax_excluded_price, :is_sale, :image)
  end
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<h1>Admin::Items#edit</h1>
<p>Find me in app/views/admin/items/edit.html.erb</p>

app/views/admin/items/index.html.erb
<h2>商品一覧</h2>
<%= link_to '商品新規登録', new_admin_item_path %>
<table class="table table-hover table-inverse">
  <tr>
  <th>商品ID</th>
  <th>商品名</th>
  <th>税抜価格</th>
  <th>ジャンル</th>
  <th>ステータス</th>
  <th colspan="3"></th>
  </tr>

  <% @items.each do |item| %>
  <tr>
    <td><%= item.id %></td>
    <td><%= item.name %></td>
    <td><%= item.tax_excluded_price %></td>
    <td><%= item.genre.name %></td>
    <td><%= item.is_sale %></td>
    <!--<%# if item.is_sale == false %>-->
    <!--<td>販売停止中</td>-->
    <!--<%# else %>-->
    <!--<td>販売中</td>-->
    <!--<%# end %>-->
  </tr>
  <% end %>
</table>


<% if @results.any? %>
<h2>検索結果</h2>
<table class="table table-hover table-inverse">
  <tr>
  <th>商品ID</th>
  <th>商品名</th>
  <th>税抜価格</th>
  <th>ジャンル</th>
  <th>ステータス</th>
  <th colspan="3"></th>
  </tr>

  <% @results.each do |item| %>
  <tr>
    <td><%= item.id %></td>
    <td><%= item.name %></td>
    <td><%= item.tax_excluded_price %></td>
    <td><%= item.genre.name %></td>
    <td><%= item.is_sale %></td>
  </tr>
  <% end %>

</table>
<% end %>

app/views/admin/items/new.html.erb
<h1>管理者#商品登録</h1>

<h1>商品新規登録</h1>
<%= form_with model: @item, url: admin_items_path(@item), method: :post, local: true do |f| %>
  <h4>商品画像</h4>
  <%= f.file_field :image, accept: "image/*" %>

  <h4>商品名</h4>
  <%= f.text_field :name %>
  <h4>商品説明</h4>
  <%= f.text_area :explanation %>
  <h4>税抜価格</h4>
  <%= f.text_field :tax_excluded_price %>
  <h4><%= f.label :ジャンル %>
  <%= f.collection_select :genre_id, Genre.all, :id, :name %></h4>
  <h4><%= f.label :販売ステータス %>
  <%= f.select :is_sale, ["販売中", "販売停止中"] , class: "btn btn-primary"%></h4>
  <%= f.submit '新規登録' %>
<% end %>

app/views/admin/items/show.html.erb
<h2>商品詳細</h2><br>
  <div>
    <% if @item.image.attached? %>
    <%= image_tag @item.image, size: "200x200" %>
    <% else %>
    <%= image_tag 'no_image', size: "200x200" %>
    <% end %>
  </div>

  <h4>商品名</h4>
    <div>
      <%= @item.name %>
    </div>
  <h4>商品説明</h4>
    <div>
      <%= @item.explanation %>
    </div>

  <h4>ジャンル</h4>
    <div>
      <%= @item.genre.name %>
    </div>

  <h4>税別価格</h4>
    <div>
      <%= @item.tax_excluded_price %>円
    </div>

  <h4>販売ステータス</h4>
    <div>
      <%= @item.is_sale %>
      <!--<%# if @item.is_sale == false %>-->
      <!--<td>販売停止中</td>-->
      <!--<%# else %>-->
      <!--<td>販売中</td>-->
      <!--<%# end %>-->
    </div>

    <%= button_to '編集する',edit_admin_item_path(@item.id), method: :get ,class: "btn btn-primary ", style: "margin-left:70%;"%>

app/views/admin/items/update.html.erb
<h1>Admin::Items#update</h1>
<p>Find me in app/views/admin/items/update.html.erb</p>