config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'orders/show'
  end
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  
  scope module: :public do
    resources :items
    resources :cart_items
    resources :address
    get 'orders/done', to: 'orders#done', as: 'orders_done'
    post "orders/confirm" => "orders#show"
    resources :orders
    root to: 'homes#top'
    get "items" => "items#index"
    get "items/:id" => "items#show"
    get "customers/mypage" => "customers#show"
    get "customers/information/edit" => "customers#edit"
    patch "customers/information" => "customers#update"
    get "customers/check" => "customers#check"
    patch "customers/leave" => "customers#leave"
    get "cart_items" => "cart_items#index"
    post "cart_items" => "cart_items#create"
    delete "cart_items" => "cart_items#destroy_all", as: "destroy_all"
    # get "address" => "address#index"
    # post "address" => "address#create"
    # get "address/:id/edit" => "address#edit"
    # patch "address/:id" => "address#update"
    # delete "address/:id" => "address#destroy"
    
  end


  namespace :admin do
    root to: 'homes#top'
    resources :customers
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items
    resources :orders
    resources :order_details
    get "genres" => "genres#index"
    post "genres" => "genres#create"
    get "genres/:id/edit" => "genres#edit"
    patch "genres/:id" => "genres#update"
    get "admin/items" => "items#index"
    get "admin/items/new" => "items#new"
    post "admin/items" => "items#create"
    # get "admin/items/:id" => "items#show"
    # get "admin/items/:id/edit" => "items/edit"
    # patch "admin/items/:id" => "items/update"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details

  enum payment_method: {credit_card: 0, transfer: 1}

  enum status: {wait_payment: 0, confirm_payment: 1, making: 2, preparing_ship: 3, finish_prepare: 4}
  #enum status: {入金待ち:0, 入金確認:1, 製作中:2, 発送準備中:3, 発送済:4}
  def self.payment_methods_i18n
    {
      credit_card: I18n.t("enums.order.payment_method.credit_card"),
      transfer: I18n.t("enums.order.payment_method.transfer")
    }
  end

  def self.statuses_i18n
    {
      wait_payment: I18n.t("enums.order.status.wait_payment"),
      confirm_payment: I18n.t("enums.order.status.confirm_payment"),
      making: I18n.t("enums.order.status.making"),
      preparing_ship: I18n.t("enums.order.status.preparing_ship"),
      finish_prepare: I18n.t("enums.order.status.finish_prepare")
    }
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
    @payment_amount = 0
    @order_details.each do |order_detail|
      @payment_amount += @order_details.sum {|order_detail| order_detail.purchase_price * order_detail.quantity }
    end
  end
  
  def update
    # @order = Order.find(params[:id])
    # @order_details = @order.order_details
    # @order.update(order_params)

    # # if @order.status == "confirm_payment"
    # if params[:order][:status] == "1"
    #   @order_details.update_all(production_status: "1")
    # end
    # redirect_to admin_order_path(@order)
    
    @order = Order.find(params[:id])
    if @order.update(order_params)
      if params[:order][:status] == "confirm_payment"
        @order_details = @order.order_details
        @order.order_details.update_all(production_status: 1)
      end
    end
    redirect_to admin_order_path(@order)
  end
  
  private
  def order_params
    params.require(:order).permit(:status)
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/show.html.erb
<h2>注文履歴詳細</h2>
  <table>
    <tr>
      <th>購入者</th>
      <td><%= @order.customer.lastname_kanji %> <%= @order.customer.firstname_kanji %></td>
    </tr>
    <tr>
      <th class= "order-show">配送先</th>
      <td>〒<%= @order.shipping_postal_code %> <%= @order.shipping_address %><br><%= @order.shipping_name %></td>
    </tr>
    <tr>
      <th class= "order-show">支払い方法</th>
      <td><%= @order.payment_method_i18n %></td>
    </tr>
    <tr>
        <!-- 注文ステータス変更　プルダウン　更新を押すとアップデート -->
      <th>注文ステータス</th>
      <td>
        <%= form_with model: @order, url: admin_order_path(@order) do |f| %><!--oreder controllerのupdateの飛ぶ-->
          <%= f.select :status, Order.statuses_i18n.invert %><!--ステータス選択 -->
          <%= f.submit "更新" ,class: "btn btn-primary btn-sm" %></td>
        <% end %>
    </tr>
  </table>

  <table>
    <tr>
      <th>商品名</th>
      <th>単価（税込）</th>
      <th>数量</th>
      <th>小計</th>
      <th>製作ステータス</th>
      <th></th>
    </tr>

    <%  @order_details.each do |order_detail| %><!--注文した商品の履歴一覧をeach分で表示　-->
      <tr>
        <td><%= order_detail.item.name %></td>
        <td><%= order_detail.purchase_price %></td>
        <td><%= order_detail.quantity %></td>
        <td><%= order_detail.purchase_price*order_detail.quantity %> </td>
        <!-- 製作ステータス変更　更新を押すと更新-->
        <td><%= form_with model: order_detail, url: admin_order_detail_path(order_detail), method: :patch do |f| %>
            <%= f.select :production_status, OrderDetail.production_statuses_i18n.invert %><!--ステータス選択 -->
            <%= f.submit "更新" ,class:"btn btn-primary btn-xs" %>
        <% end %>
        </td>
      </tr>
    <% end %>
  </table>


    <div>
     <h4>商品合計     <%= @payment_amount %>円</h4>
     <h4>送料　　　    <%= 800 %>円</h4>
     <h4>請求金額合計　<%= (@payment_amount + 800) %>円</h4>
    </div>

</div>