config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'orders/show'
  end
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  
  scope module: :public do
    resources :items
    resources :cart_items
    resources :address
    get 'orders/done', to: 'orders#done', as: 'orders_done'
    post "orders/confirm" => "orders#show"
    resources :orders
    root to: 'homes#top'
    get "items" => "items#index"
    get "items/:id" => "items#show"
    get "customers/mypage" => "customers#show"
    get "customers/information/edit" => "customers#edit"
    patch "customers/information" => "customers#update"
    get "customers/check" => "customers#check"
    patch "customers/leave" => "customers#leave"
    get "cart_items" => "cart_items#index"
    post "cart_items" => "cart_items#create"
    delete "cart_items" => "cart_items#destroy_all", as: "destroy_all"
    # get "address" => "address#index"
    # post "address" => "address#create"
    # get "address/:id/edit" => "address#edit"
    # patch "address/:id" => "address#update"
    # delete "address/:id" => "address#destroy"
    
  end


  namespace :admin do
    root to: 'homes#top'
    resources :customers
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items
    resources :orders
    resources :order_details
    get "genres" => "genres#index"
    post "genres" => "genres#create"
    get "genres/:id/edit" => "genres#edit"
    patch "genres/:id" => "genres#update"
    get "admin/items" => "items#index"
    get "admin/items/new" => "items#new"
    post "admin/items" => "items#create"
    # get "admin/items/:id" => "items#show"
    # get "admin/items/:id/edit" => "items/edit"
    # patch "admin/items/:id" => "items/update"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
  with_options presence: true do
    validates :name, presence: true
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genres = Genre.all
    @genre = Genre.new #データを新規登録するためのインスタンス生成
    # @genre.save #データをデータベースに保存するためのsaveメソッド実行
    # redirect_to admin_genres_path
  end

  def create
    @genre = Genre.new(genre_params) #データを新規登録するためのインスタンス生成
    @genre.save #データをデータベースに保存するためのsaveメソッド実行
    redirect_to admin_genres_path #トップ画面へリダイレクト
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      render :edit
    end
  end
  
  private
  
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/edit.html.erb
<h1>管理者#ジャンル編集</h1>

<h2>ジャンル一覧・追加</h2>

<%= form_with model: @genre, url: admin_genre_path, method: :patch do |f| %>
  <h4>ジャンル名</h4>
  <%= f.text_field :name %>
  <%= f.submit "変更を保存" %>
<% end %>

<!--<%# redirect_to admin_genres_path %>-->

app/views/admin/genres/index.html.erb
<h2>ジャンル一覧・追加</h2>

<%= form_with model: @genre, url: admin_genres_path do |f| %>
  <h4>ジャンル名</h4>
  <%= f.text_field :name %>
  <%= f.submit '新規登録' %>

<table class="table table-hover table-inverse">
  <tr>
  <th>ジャンル</th>
  <th></th>
  <th colspan="3"></th>
  </tr>

  <% @genres.each do |genre| %>
  <tr>
    <td><%= genre.name %></td>
    <td><%= link_to edit_admin_genre_path(genre) do %>編集する<% end %></td>
  </tr>
  <% end %>

</table>
  
<% end %>

app/views/admin/genres/update.html.erb
<h1>管理者#ジャンルデータ更新</h1>