config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'orders/show'
  end
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  
  scope module: :public do
    resources :items
    resources :cart_items
    resources :address
    get 'orders/done', to: 'orders#done', as: 'orders_done'
    post "orders/confirm" => "orders#show"
    resources :orders
    root to: 'homes#top'
    get "items" => "items#index"
    get "items/:id" => "items#show"
    get "customers/mypage" => "customers#show"
    get "customers/information/edit" => "customers#edit"
    patch "customers/information" => "customers#update"
    get "customers/check" => "customers#check"
    patch "customers/leave" => "customers#leave"
    get "cart_items" => "cart_items#index"
    post "cart_items" => "cart_items#create"
    delete "cart_items" => "cart_items#destroy_all", as: "destroy_all"
    # get "address" => "address#index"
    # post "address" => "address#create"
    # get "address/:id/edit" => "address#edit"
    # patch "address/:id" => "address#update"
    # delete "address/:id" => "address#destroy"
    
  end


  namespace :admin do
    root to: 'homes#top'
    resources :customers
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items
    resources :orders
    resources :order_details
    get "genres" => "genres#index"
    post "genres" => "genres#create"
    get "genres/:id/edit" => "genres#edit"
    patch "genres/:id" => "genres#update"
    get "admin/items" => "items#index"
    get "admin/items/new" => "items#new"
    post "admin/items" => "items#create"
    # get "admin/items/:id" => "items#show"
    # get "admin/items/:id/edit" => "items/edit"
    # patch "admin/items/:id" => "items/update"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  
  def address_display
    '〒' + post_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  #validates :amount, presence: true
  #validates :tax_excluded_price, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :cart_items
  has_many :addresses
  has_many :orders
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :lastname_kanji, presence: true
  validates :firstname_kanji, presence: true
  validates :lastname_kana, presence: true
  validates :lastname_kana, presence: true
  validates :post_code, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  #validates :email, presence: true, uniqueness: true

  # is_deletedがfalseならtrueを返す
  def active_for_authentication?
    super && (is_deleted == false)
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
  with_options presence: true do
    validates :name, presence: true
  end
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items
  #has_many :order_details
  enum is_sale: {"販売中":true, "販売停止中":false}
  #with_options presence: true do
   #validates :name, presence: true
   #validates :explanation, presence: true
   #validates :tax_excluded_price, presence: true
   
  #end
  has_one_attached :image
  
  def tax_included_price
    (self.tax_excluded_price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details

  enum payment_method: {credit_card: 0, transfer: 1}

  enum status: {wait_payment: 0, confirm_payment: 1, making: 2, preparing_ship: 3, finish_prepare: 4}
  #enum status: {入金待ち:0, 入金確認:1, 製作中:2, 発送準備中:3, 発送済:4}
  def self.payment_methods_i18n
    {
      credit_card: I18n.t("enums.order.payment_method.credit_card"),
      transfer: I18n.t("enums.order.payment_method.transfer")
    }
  end

  def self.statuses_i18n
    {
      wait_payment: I18n.t("enums.order.status.wait_payment"),
      confirm_payment: I18n.t("enums.order.status.confirm_payment"),
      making: I18n.t("enums.order.status.making"),
      preparing_ship: I18n.t("enums.order.status.preparing_ship"),
      finish_prepare: I18n.t("enums.order.status.finish_prepare")
    }
  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  
  enum production_status: {impossible_manufacture:0, waiting_manufacture:1, manufacturing:2, finish:3}

  def self.production_statuses_i18n
    {
      impossible_manufacture: I18n.t("enums.order_detail.production_status.impossible_manufacture"),
      waiting_manufacture: I18n.t("enums.order_detail.production_status.waiting_manufacture"),
      manufacturing: I18n.t("enums.order_detail.production_status.manufacturing"),
      finish: I18n.t("enums.order_detail.production_status.finish")
    }
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genres = Genre.all
    @genre = Genre.new #データを新規登録するためのインスタンス生成
    # @genre.save #データをデータベースに保存するためのsaveメソッド実行
    # redirect_to admin_genres_path
  end

  def create
    @genre = Genre.new(genre_params) #データを新規登録するためのインスタンス生成
    @genre.save #データをデータベースに保存するためのsaveメソッド実行
    redirect_to admin_genres_path #トップ画面へリダイレクト
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      render :edit
    end
  end
  
  private
  
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @order = Order.all
    @order = Order.includes(:order_details).all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def index
    @items = Item.all
    @item = Item.new
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params) #データを新規登録するためのインスタンス生成
      if @item.save
      redirect_to admin_item_path(@item)
      else
      render "show"
      end
  end

  def show
    @item = Item.find(params[:id])
    @items = Item.all
  end

  def edit
  end

  def update
  end

  private

  def item_params
    params.require(:item).permit(:genre_id, :name, :explanation, :tax_excluded_price, :is_sale, :image)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :search

  def search
    @q = Item.ransack(params[:q])
    if params[:q].present?
      @results = @q.result
    else
      @results = []
    end
  end
  
  def after_sign_in_path_for(resource)
    customers_mypage_path
  end
  
  def after_sign_out_path_for(resource)
      root_path
  end
  
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<link 
  href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" 
  rel="stylesheet" 
  integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" 
  crossorigin="anonymous"
>

    <script src="https://kit.fontawesome.com/62d9c70015.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <header>
      <%= link_to 'NaganoCake', (admin_signed_in? ? admin_top_path : root_path ), class: "logo" %><i class="fa-solid fa-cake-candles"></i>
      <% if admin_signed_in? %>
        <%= link_to '商品一覧', admin_items_path %>
        <%= link_to admin_customers_path do %>会員一覧<% end %>
        <%= link_to '注文履歴一覧', admin_root_path %>
        <%= link_to 'ジャンル一覧', admin_genres_path %>
        <%= link_to destroy_admin_session_path, method: :delete do %>ログアウト<% end %>
        <%= search_form_for @q, url: admin_items_path do |f| %>
        <%= f.label :name_cont, '商品名' %>
        <%= f.search_field :name_cont %>
        <br>
        <%= f.submit '検索' %>
      <% end %>
      <% elsif customer_signed_in? %>
      <body id="wrapper" style="background-color: white; font-family: HiraMinPro-W6; color: #000000;">
        <%#= link_to root_path do %><%# end %>
        <%= link_to customers_mypage_path do %>マイページ<% end %>
        <%= link_to items_path do %>商品一覧<% end %>
        <%= link_to 'カート', cart_items_path %>
        <%= button_to destroy_customer_session_path, method: :delete, class: 'nav-link text-light' do %>ログアウト<% end %>
        
        <p>ようこそ、<%= current_customer.lastname_kanji + current_customer.lastname_kana %>さん!</p>
        
      <% else %>
        <%= link_to root_path do %>LOGO<% end %>
        <%= link_to '商品一覧', items_path %>
        <%= link_to new_customer_registration_path do %>新規登録<% end %>
        <%= link_to new_customer_session_path do %>ログイン<% end %>
      <% end %>

      <%#= form_with model: @search, url: admin_items_path, local: true, method: :get do |f| %>
  <%#= f.text_field :q, :word %>
  <%#= f.select :q, :range, options_for_select([['User']['Book']]) %>
  <%#= f.select :q, :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backward_match"], ["部分一致","partial_match"]]) %>
  <%#= f.submit "検索", class: "btn btn-primary" %>
<%# end %>
    </header>

    <%= yield %>
<script 
  src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" 
  integrity="sha384-Qo8tQJwoexv3zYp1Mz3a6K6J6tcQGuK5OgHZ7VZaMsINo5th6oUvm1ciS+HIatnF" 
  crossorigin="anonymous">
</script>
  </body>
  
  <footer>Copyright © Infratop Inc. All Rights Reserved.</footer>
</html>